 export const EmployeeActionTypes = {
    
    FETCH_EMPLOYEES_PENDING : 'FETCH_EMPLOYEES_PENDING',
    FETCH_EMPLOYEES_SUCCESS : 'FETCH_EMPLOYEES_SUCCESS',
    FETCH_EMPLOYEES_ERROR : 'FETCH_EMPLOYEES_ERROR',
    SEARCH_EMPLOYEE:'SEARCH_EMPLOYEE',
    UPDATE_EMPLOYEE_SUCCESS: 'UPDATE_EMPLOYEE_SUCCESS',
    UPDATE_EMPLOYEE_ERROR: 'UPDATE_EMPLOYEE_ERROR',
    ADD_NEW_EMPLOYEE_SUCCESS:'ADD_NEW_EMPLOYEE_SUCCESS',
    ADD_NEW_EMPLOYEE_ERROR : 'ADD_NEW_EMPLOYEE_ERROR',
    DELETE_EMPLOYEE_SUCCESS:'DELETE_EMPLOYEE_SUCCESS',
    DELETE_EMPLOYEE_ERROR:'DELETE_EMPLOYEE_ERROR'

}

